Repository Birdbh/Engicoders, pull requests merged in 2024-04, with the labels that each got.

#229 Add Upgrade System
  src/flaskr/__init__.py
  src/flaskr/db.sql
  src/flaskr/payment.py
  src/flaskr/routing.py
  src/flaskr/static/style.css
  src/flaskr/templates/base.html
  src/flaskr/templates/main/home.html
  src/flaskr/templates/main/upgrade.html
  src/flaskr/templates/main/welcome.html
  src/flaskr/upgrade.py
  src/flaskr/user.py
  tests/test_auth.py
  tests/test_login.py
  tests/test_upgrade.py
Labels: Feature

#233 Bug needs to be fixed when a non-premium user tries to select data from Thinkspeak API.
  src/flaskr/home.py
Labels: bug

#234 Testing is incomplete and needs additions for home and data additions for managing upload.
  UPLOADED_DATA/data.xlsx
  tests/test_DataUpload.py
  tests/test_home.py
Labels: chore

#237 added m4 to deliverable folder
  Deliverables/M4_Testing_Update_Report.pdf
Labels: documentation

#238 Cleaning imports
  Deliverables/M3.md
  Deliverables/M3_Formal_Analysis_and_Architecture.pdf
  Requirements/COSC310 Class Diagram.png
  Requirements/COSC310 Use Case Diagram .png
  Requirements/COSC310_Class_Diagram.png
  Requirements/COSC310_Use_Case_Diagram.png
  Scrum meetings/SCRUM_MEETING_WEEK_(10).pdf
  Scrum meetings/SCRUM_MEETING_WEEK_(4).pdf
  Scrum meetings/SCRUM_MEETING_WEEK_(5).pdf
  Scrum meetings/SCRUM_MEETING_WEEK_(6).pdf
  Scrum meetings/SCRUM_MEETING_WEEK_(7).pdf
  Scrum meetings/SCRUM_MEETING_WEEK_(9).pdf
  src/flaskr/db.sql
  src/flaskr/home.py
  src/flaskr/login.py
  src/flaskr/payment.py
  src/flaskr/register.py
  src/flaskr/routing.py
  src/flaskr/upgrade.py
  src/sensors/Cleanser.py
  src/sensors/Prediction.py
  tests/test_Chart.py
  tests/test_Cleanser.py
  tests/test_DataGeneration.py
  tests/test_DataUpload.py
  tests/test_DecoratorPattern.py
  tests/test_Prediction.py
  tests/test_alarm.py
  tests/test_alarmManager.py
  tests/test_db.py
  tests/test_home.py
  tests/test_login.py
  tests/test_register.py
  tests/test_sensor.py
  tests/test_superUser.py
  tests/test_upgrade.py
  tests/test_user.py
Labels: chore

#243 Fix bug for non-public fields and creates flash message that cleanse must be selected in order to predict data.
  src/flaskr/home.py
  src/flaskr/routing.py
Labels: bug

#242 added scrum meeting wk 13 to folder
  Scrum meetings/SCRUM_MEETING_WEEK_(13).pdf
Labels: documentation

#246 Adjust Home.py form input so that the fields are entered in a box that holds the fields horizontal and re-sizes.
  src/UPLOADED_DATA/data.xlsx
  src/flaskr/static/style.css
  src/flaskr/templates/main/home.html
Labels: Task

#252 Added downloading per issue 38
  src/flaskr/templates/main/home.html
Labels: Feature

#236 added fixed M2 to deliverables
  Deliverables/M2_ Project_Description_and_Requirements(2).pdf
  Deliverables/M2_Project_Description_and_Requirements.pdf
Labels: documentation, chore

#251 Add edge test cases to home form input, specifically with conflicting modifiers such as prediction and cleansing.
  UPLOADED_DATA/data.xlsx
  tests/test_home.py
Labels: chore

#255 fix chart and test_chart
  src/Chart.py
  tests/test_Chart.py
Labels: bug

#265 added final scrum meeting to folder
  Scrum meetings/SCRUM_MEETING_WEEK_(14).pdf
Labels: documentation

#266 Update README.md
  README.md
Labels: chore

#244 added m5 base doc to the folder
  Deliverables/Milestone_5_Report.pdf
Labels: documentation
