Repository Birdbh/Engicoders, pull requests merged in 2024-03, with the labels that each got.

#78 Write login() functionality with flask web application for users to check username and password with SQlite database for a match
  src/flaskr/__pycache__/auth.cpython-39.pyc
  src/flaskr/auth.py
  tests/__pycache__/conftest.cpython-39-pytest-8.0.1.pyc
  tests/__pycache__/test_auth.cpython-39-pytest-8.0.1.pyc
  tests/conftest.py
  tests/test_auth.py
Labels: Feature

#77 Create Sensor Object class that outlines the attributes of a sensor object and 3 main functions that can be used on a sensor object
  src/__pycache__/__init__.cpython-39.pyc
  src/sensors/__pycache__/__init__.cpython-39.pyc
  src/sensors/__pycache__/sensor.cpython-39.pyc
  src/sensors/sensor.py
  tests/__pycache__/test_sensor.cpython-39-pytest-8.0.1.pyc
  tests/test_sensor.py
Labels: Feature

#83 Removing all pycache files per issue #82
  src/__pycache__/__init__.cpython-39.pyc
  tests/__pycache__/conftest.cpython-39-pytest-8.0.1.pyc
  tests/__pycache__/test_auth.cpython-39-pytest-8.0.1.pyc
  tests/__pycache__/test_sensor.cpython-39-pytest-8.0.1.pyc
Labels: chore

#79 updated the python exploratory file
  Exploratories/python_information.pdf
Labels: Exploration

#88 Add files via upload
  src/flaskr/db.sql
Labels: Task

#113 Birdbh/issue109
  src/DataGeneration.py
  src/flaskr/__pycache__/auth.cpython-39.pyc
  src/sensors/__pycache__/sensor.cpython-39.pyc
  tests/test_DataGeneration.py
Labels: Task

#121 Birdbh/issue110
  src/DataGeneration.py
  tests/test_DataGeneration.py
Labels: Feature

#125 formatted M3 and added the sequence diagram
  Deliverables/Milestone 3 Report.pdf
Labels: documentation

#128 Adding cleanser functionalities
  src/sensors/Cleanser.py
  tests/test_Cleanser.py
Labels: Feature

#137 Birdbh/issue135 -> Creation of Base.html document with correct Jinja notaton, including header, footer, title, links
  src/flaskr/static/base.html
  src/flaskr/static/style.css
  src/flaskr/static/testLayout.html
  src/flaskr/templates/auth/login.html
  src/flaskr/templates/auth/register.html
  src/flaskr/templates/base.html
  src/flaskr/templates/main/home.html
Labels: Feature

#136 added scrum wk 10 to scrum meetings
  Scrum meetings/SCRUM MEETING WEEK (10).pdf
Labels: documentation

#142 Cleanser Class needs to cleanse the values that are stored in the sensor object values.
  src/sensors/Cleanser.py
  tests/test_Cleanser.py
Labels: chore

#140 Birdbh/issue134 -> Development of main.html to match the form guidlines needed for main.py
  src/flaskr/templates/main/home.html
Labels: Feature

#144 Birdbh/issue143 -> Addition of Functionality for sensors to get and set the values of the date range and values
  src/DataGeneration.py
  src/sensors/sensor.py
  tests/test_sensor.py
Labels: chore

#154 fixed cleanser and added remove min and max
  src/sensors/Cleanser.py
  tests/test_Cleanser.py
Labels: Feature

#163 Add routing issue155
  .flaskenv
  src/flaskr/__init__.py
  src/flaskr/auth.py
  src/flaskr/routing.py
  src/flaskr/templates/base.html
Labels: Feature

#131 Create PythonRequirements.bat per #124
  PythonRequirements.bat
Labels: chore

#174 added scrum meeting wk 11 to scrum meetings
  Scrum meetings/SCRUM_MEETING_WEEK_(11).pdf
Labels: documentation

#164 added my pdf of what chart.js files should look like
  Exploratories/Chart.js_exploratory.pdf
Labels: Exploration

#151 Birdbh/issue145 -> Create Prediction class that will take a sensor object and fill the prediction field based on a SARIMAX model
  src/Prediction.py
  src/sensors/sensor.py
  tests/test_Prediction.py
Labels: Feature, Task

#178 Birdbh/issue171 -> Refactor code to implement the Decorator pattern between cleanser, sensor, and prediction.
  Exploratories/Chart.js_exploratory.pdf
  Scrum meetings/SCRUM_MEETING_WEEK_(11).pdf
  src/DataGeneration.py
  src/sensors/Cleanser.py
  src/sensors/DecoratorPattern.py
  src/sensors/Prediction.py
  src/sensors/sensor.py
  test.ipynb
  tests/test_DecoratorPattern.py
  tests/test_Prediction.py
Labels: Feature

#177 added m4 base to the deliverables file
  Deliverables/M4_Testing_Update_Report.pdf
Labels: documentation

#186 Set up Basic Analysis for testing workflow for CI/CD with Github Actions (Vanilla Version)
  .github/workflows/python-app.yml
  requirements.txt
  tests/test_db.py
Labels: chore

#188 Brkykrclk/issue180
  src/alarmManager.py
  src/sensors/alarm.py
  tests/test_alarm.py
  tests/test_alarmManager.py
Labels: Feature, Task

#187 Implement Decorator Pattern for sensor, cleanser, and prediction -> including: addition of classes, modification of necessary tests.
  src/sensors/Cleanser.py
  src/sensors/DecoratorPattern.py
  src/sensors/Prediction.py
  src/sensors/sensor.py
  tests/test_DecoratorPattern.py
  tests/test_Prediction.py
Labels: Task

#191 Create User Class per issue 165
  requirements.txt
  src/flaskr/user.py
  tests/test_user.py
Labels: Feature

#193 Update README to better format the user requirments and explain briefly how to run the project.
  README.md
Labels: chore

#194 Add Log-in Functionality per issue 51
  src/flaskr/__init__.py
  src/flaskr/auth.py
  src/flaskr/login.py
  src/flaskr/loginPage.py
  src/flaskr/register.py
  src/flaskr/routing.py
  src/flaskr/templates/auth/login.html
  src/flaskr/templates/base.html
  src/flaskr/user.py
  tests/test_login.py
  tests/test_user.py
Labels: Feature

#202 added chart class and full test suite
  src/Chart.py
  tests/test_Chart.py
Labels: Feature

#209 Updating home.py and adding test class for it
  src/Chart.py
  src/flaskr/__init__.py
  src/flaskr/home.py
  src/flaskr/routing.py
  src/flaskr/templates/base.html
  src/flaskr/templates/main/home.html
  tests/test_Chart.py
  tests/test_home.py
Labels: Task

#206 added the testing implementation and automation section to M4
  Deliverables/M4_Testing_Update_Report.pdf
Labels: documentation

#216 Update chart selection for three chart types, include prediction & cleansing to charting, add prediction input date fields.
  src/flaskr/home.py
  src/flaskr/templates/main/home.html
  src/sensors/Prediction.py
  src/sensors/sensor.py
  tests/test_DecoratorPattern.py
  tests/test_sensor.py
Labels: Feature

#217 added wk 12 scrum meeting to the folder
  Scrum meetings/SCRUM_MEETING_WEEK_(12).pdf
Labels: documentation

#197 Create SuperUser Class
  src/flaskr/db.py
  src/flaskr/db.sql
  src/flaskr/login.py
  src/flaskr/user.py
  tests/conftest.py
  tests/data.sql
  tests/test_db.py
  tests/test_register.py
  tests/test_superUser.py
  tests/test_user.py
Labels: bug, Feature

#228 Add Data upload functionality so that users can upload a csv and that data can be parsed as sensor data.
  requirements.txt
  src/DataUpload.py
  src/UPLOADED_DATA/data.xlsx
  src/flaskr/__init__.py
  src/flaskr/home.py
  src/flaskr/routing.py
  src/flaskr/templates/main/home.html
Labels: bug, chore, Feature
